### ISSUE TITLE
Interop with wsl.exe export/import and/or docker export/load

### ISSUE THREAD

**Issue by Martin-Nyaga** [DDoSolitary/LxRunOffline#115]
I'm curious about whether LxRunOffline is capable of inter-operating with either:
- Distros exported directly from WSL: `wsl.exe --export Distro distro.tar`
- Containers exported from docker: `docker export --output=test-distro.tar test-container`

Can LXRunOffline be able to import these? And vice versa, can images exported by LXRunOffline be imported using `docker` or `wsl.exe` directly?

**Comment by Martin-Nyaga** [comment]
In case anyone lands here, the answer is, apparently, yes, at least from docker -> WSL through LXRunOffline. I have been able to successfully use LXRunOffline to import a docker image exported through `docker export` directly into WSL. The only gotchas are that the WSL distro loses any environment variables that were set in the docker image.

**Comment by DDoSolitary** [comment]
I'm really sorry that I totally forget this issue until you posted the comment (because I accidentally deleted it from my to-do list) 

Happy to see that you have figured it out yourself. As for the environment variables, the `docker export` command doesn't save them to the exported tar archive so unfortunately there's nothing I can do on my side.

**Comment by Martin-Nyaga** [comment]
Thanks for the response @DDoSolitary. For our use case, the environment variables are not a big problem. The current behaviour is perfectly acceptable.
