### ISSUE TITLE
The package was not found with the source(s) listed.  Source(s): 'https://roswin.azurewebsites.net/api/v2'

### ISSUE THREAD

**Issue by Marietto2008** [DDoSolitary/LxRunOffline#120]
choco install lxrunoffline -y
Chocolatey v0.10.15
Installing the following packages:
lxrunoffline
By installing you accept licenses for the packages.
lxrunoffline not installed. The package was not found with the source(s) listed.
 Source(s): 'https://roswin.azurewebsites.net/api/v2'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - lxrunoffline - lxrunoffline not installed. The package was not found with the source(s) listed.
 Source(s): 'https://roswin.azurewebsites.net/api/v2'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare

**Comment by DDoSolitary** [comment]
Obviously you're not using Chocolatey's official source.

**Comment by Marietto2008** [comment]
a solution is appreciated.

**Comment by DDoSolitary** [comment]
First of all, I don't know why you set your chocolatey's source to a non-official one so I can't give a solution quickly and confidently.
Second, this is not Chocolatey support forum so I'm not responsible for solving a problem that is actually related to Chocolatey rather than LxRunOffline
Third, if I have a lot of spare time I would be willing to help you but unfortunately I'm quite busy currently.
Finally, I've already pointed out the direct cause of your problem and I closed the issue because it is not related to LxRunOffline. If you want help from somebody who is not responsible for solving your problem, DO NOT make arbitrary assumptions about his thoughts and say he's "totally wrong" based on that assumption.

**Comment by Marietto2008** [comment]
are u a programmer,right ? so you should know the meaning of "IF".

**Comment by DDoSolitary** [comment]
"if" can have different semantics in a programming language and a natural language. If expressed in a programming language like C, your words sounds more likely to be `if (__builtin_expect(you think blabla, 1)) { you're totally wrong }` to me , which is quite offensive.

If you want to get your problem solved, I would suggest you stop wasting my time and ask your question in a more appropriate place, like Chocolatey's Gitter chat (which can be found in the bottom right corner of the package page) or [Super User](superuser.com).

**Comment by Marietto2008** [comment]
Mine is a criticism addressed only to those programmers who cannot put themselves in the shoes of others and that believe that everyone is able like them to have a programmer's mindset, for this reason they are not inclined to help. And when they do, they give even more technical advices, because they are victims of a mental bias, that of excessive identification with their "love" object. If you are not like this, better for all of us.
