### ISSUE TITLE
Help Export Commands

### ISSUE THREAD

**Issue by rescenic** [DDoSolitary/LxRunOffline#123]
The output file that I exported without specifying the extension are Alpine and Alpine.xml.
![Alpine](https://i.ibb.co/Rj7wyTv/18-05-2020-545-16-59-28.png)
Can I rename it or leave it?
![Alpine2](https://i.ibb.co/gVJNDcP/18-05-2020-544-16-58-00.png)
So, the right command to export it is:
`lxrunoffline export -n Alpine -f "C:\Alpine\Alpine.tar.gz"`? 

If I install lxrunoffline in another computer and use register parameter, will it works and the data inside it safe?

**Comment by rescenic** [comment]
Wow, amazing, it works. I just renamed it.
![Alpine3](https://i.ibb.co/Zf5XQY1/18-05-2020-546-17-06-39.png)

**Comment by DDoSolitary** [comment]
Sorry for the late response, and happy to see that you've made it working.

>  Can I rename it or leave it?

The export command won't be influenced  by the file extension, because it always creates archives in the format of ".tar.gz". However, the install command relies on libarchive the detect file format, which may require a correct file extesnion (I'm not sure, haven't checked).

Please also note that if you don't want to lose configuration of your exported distro, you also need to rename `Alpine.xml` to `Alpine.tar.gz.xml` when renaming `Alpine` to `Alpine.tar.gz`.

> If I install lxrunoffline in another computer and use register parameter, will it works and the data inside it safe?

The register command is for scenarios like that you installed a distro in a USB stick and plugged it into another computer. If that is the case, it should work in theory. If you want to use the exported distro on another computer, the install command should be used.
