### ISSUE TITLE
Can't access WSL2 after moving

### ISSUE THREAD

**Issue by abalter** [DDoSolitary/LxRunOffline#131]
I originally installed my instance through the app store. Today I tried to move it using 

    lxrunoffline m -n Ubuntu -d C:\\Ubuntu

The directory appeared where expected. But it became inaccessible. Also instead of showing up as a directory with `rootfs/[home|bin|etc.]`,  `C:\\Ubuntu` just has a file called `ext4.vhdx`. 

I tried to register it with

```
C:\Users\ariel>lxrunoffline rg -n Ubuntu -d C:\\Ubuntu                                                                  [ERROR] Couldn't open the file "\\?\C:\Ubuntu\ext4.vhdx".                                                               Reason: The process cannot access the file because it is being used by another process.     
```

I also tried installing with 

```
C:\Users\ariel>lxrunoffline i -n Ubuntu -d C:\\wsl -f C:\\Ubuntu\ext4.vhdx                                              [ERROR] Couldn't open the file "C:\\Ubuntu\ext4.vhdx".                                                                  Reason: The process cannot access the file because it is being used by another process. 
```

I tried restarting the computer a couple of times, but I still get the "used by another process" message.

How can I get my distro back given that I only have a `vhdx` file now?

**Comment by DDoSolitary** [comment]
What do you mean by saying "But it became inaccessible"? How did you access it and what's the error message?

If it is a WSL2 distro, it is expected that the directory only contains ext4.vhdx. This is because WSL2 internally uses Hyper-V for virtualization and thus uses a vhdx virtual disk to store Linux files.

**Comment by abalter** [comment]
>What do you mean by saying "But it became inaccessible"? How did you access it and what's the error message?

When I tried `bash` or `wsl` at a CMD prompt it timed out. When I opened MobaXTerm my usual wsl tabs opened, but then they timed out and closed and the whole app closed.

>If it is a WSL2 distro, it is expected that the directory only contains ext4.vhdx. This is because WSL2 internally uses Hyper-V for virtualization and thus uses a vhdx virtual disk to store Linux files.

In that case, how do I reinstall or re-register it? My attempts gave the error shown about "used by another process" even after restarting the device.

Also, without a `rootfs` folder, how would I access the files form Windows? A "vanilla" installed WSL has those.

Incidentally, I installed another wsl2 instance through the app store, and was able to successfully move that one using lxrunoffline. So my main issue right now is to be able to get to the files in the `.vhdx` file created by the first move attempt.

**Comment by DDoSolitary** [comment]
> In that case, how do I reinstall or re-register it? My attempts gave the error shown about "used by another process" even after restarting the device.

It is incorrect to use register or install commands in the way you described. The register command is for registering a directory that has NOT been registered (e.g. when a distro is installed in a USB stick and inserted to a new computer). The install command is for installing a NEW distro from an archive file containing the required files.

I'm not very sure about why the vhdx file is in use. Probably it's because you've tried launching the distro so WSL itself has it opened. If that is the case, running `wsl --shutdown` will shutdown WSL and release the file.

> So my main issue right now is to be able to get to the files in the .vhdx file created by the first move attempt.

I would suggest try running "unregister" and then "register" on the old distro. If this doesn't work, it is likely that either there's something wrong with WSL(2) or the files required to launch the distro in ext4.vhdx in corrupt. If WSL is refusing to load the vhdx file, the easiest way I can come up with to recover the files inside is to configure a Linux virtual machine in Hyper-V and attach the vhdx file to it. Inside the vhdx file is normal ext4 filesystem so you should be able to mount it normally and read the files.

**Comment by azraelkuan** [comment]
@DDoSolitary the update solved my problem, thanks.

**Comment by awesome-libra** [comment]
I fixed same problem by "netsh winsock reset"
