### ISSUE TITLE
switch to wsl 2 or use wsl 2 by default

### ISSUE THREAD

**Issue by Xephobia** [DDoSolitary/LxRunOffline#133]
hello, when creating a distro the distro is created on wsl 1. How to use wsl 2 ?

**Comment by minghu6** [comment]
> hello, when creating a distro the distro is created on wsl 1. How to use wsl 2 ?

In theory, it should be `.\LxRunOffline.exe i -v 2 -n <DistribName> -d <InstallDir> -f <DistribFile>`
Or just ommit the `-v 2`, it will use latest value 2 as default.

However, It seems that version setting for wsl not works, it just creates distribution using wsl1 for all.

**Comment by DDoSolitary** [comment]
@Xephobia Creating WSL2 distros isn't supported. However, you can convert an existing distro to WSL2 using `wsl --set-version <name> 2`

@minghu6 `'-v` is for filesystem version rather than WSL version. During the evolution of WSL1, it has used different versions of file systems which use different directory layout and file attributes. So it has nothing to do with WSL2.

**Comment by minghu6** [comment]
> @Xephobia Creating WSL2 distros isn't supported. However, you can convert an existing distro to WSL2 using `wsl --set-version <name> 2`
> 
> @minghu6 `-v` is for filesystem version rather than WSL version. During the evolution of WSL1, it has used different versions of file systems which use different directory layout and file attributes. So it has nothing to do with WSL2. (Probably I should make it clear in the help text.)

En, maybe the reason is the wincpp style makes me uncomfortable to read its detiails.
 I have installde ditrib from miscrosoft store and move it using `LxRunOffline move` as a install-distribution-by-wsl2 workaround.
