### ISSUE TITLE
WSL2

### ISSUE THREAD

**Issue by AceHack** [DDoSolitary/LxRunOffline#139]
Does this work with WSL2 including GPU support in insider builds?

**Comment by jamesyangget** [comment]
YES

**Comment by DDoSolitary** [comment]
Most of the commands work with WSL2, but there are several limitations because reading/writing WSL2's underlying filesystem (which is a vhdx file) hasn't been supported.

- The `install` command can not install WSL2 distros directly, but you can install a WSL1 distro and then convert it to WSL2 using `wsl --ser-version`
- The `export` command doesn't support WSL2 distros.

As far as I know, the GPU support doesn't introduce any file system changes, so compatibility is same as older versions of WSL2.
