### ISSUE TITLE
kali kali I need kali please :)

### ISSUE THREAD

**Issue by creazyboyone** [DDoSolitary/LxRunOffline#148]
![image](https://user-images.githubusercontent.com/23612645/95016204-fd2a1800-0640-11eb-863e-f3ad5adf4f0c.png)
as you can see !

I need to move my kali from C:\ to E:\ but failure,
it can move rootfs only,
and when i touch a new file,   can't see it on E:\

**Comment by DDoSolitary** [comment]
Your first attempt of moving has already succeeded (just ignore the warnings, as they're harmless). So if your second invocation failed because you're actually trying to move to the same directory. Please try to run it and let me know if it is working correctly.

**Comment by creazyboyone** [comment]
看了下，原来是国人，重新试了一下可以了，这个警告有点迷惑，毕竟支持列表里面没写支持Kali，还以为失败了23333，翻译一下给老外看
i try it again, it work! thx! just ignore the warnings...

**Comment by DDoSolitary** [comment]
> 看了下，原来是国人

Yes, I'm Chinese but I try to keep using English in the issue comments for other users.

> 这个警告有点迷惑，毕竟支持列表里面没写支持Kali，还以为失败了23333

Probably I should make it output some messages like "operation succeeded" as the warnings has been confusing a lot of people.

**Comment by creazyboyone** [comment]
so, i have some suggest ?
1. change the output message.
2. when i run the copy/move commands( it may need some time), and type Ctrl + C at the same time to stop the action, some bug may be appear ( ask : are you sure to exit ? Y or N)
3. add kali-linux to support list? or do other test first?
4. add some warnings/tips before move file, some linux files(or kali only) will be quarantined by antivirus software.(Huorong)
5. add a ProgressBar?

**Comment by DDoSolitary** [comment]
> change the output message.

Sure, I'll do this when I have some time.

> when i run the copy/move commands( it may need some time), and type Ctrl + C at the same time to stop the action, some bug may be appear ( ask : are you sure to exit ? Y or N)

No, Ctrl+C is expected to stop the program and I don't want to add a lot of "do you want to do this?" confirmations. You're at your own risk when doing so. Acutally, data loss is very unlikely to happen because files will only be deleted at the end of a move operation, so normally you just need to delete some half-created distros using the `uninstall` or `unregister` commands in case of accidental exiting.

> add kali-linux to support list? or do other test first?

The "support list" is simply a list of places where you can find the tar files for installation. I'm not very familiar with Kali so I can add it to the list if you let me know the place to find the download links.

> add some warnings/tips before move file, some linux files(or kali only) will be quarantined by antivirus software.(Huorong)

No, the same reason as the second one.

> add a ProgressBar?

It is pretty hard to add a process bar for copying/moving because it's impossible to know the exact number of files to be processed before they've been processed. However, I'm considering to display a message about the number of files that has been processed, so that users can know the tool is actually working rather than gets stuck on something.
