### ISSUE TITLE
Error: 0x80070002 when I try to install Ubuntu

### ISSUE THREAD

**Issue by MtMao** [DDoSolitary/LxRunOffline#18]
I download file from [https://wsldownload.azureedge.net/16.04.2-server-cloudimg-amd64-root.tar.gz](https://wsldownload.azureedge.net/16.04.2-server-cloudimg-amd64-root.tar.gz)
then use LxRunOffline to install it.
`lxrunoffline install -n Ubuntu -d A:\WSL\Ubuntu -f A:\16.04.2-server-cloudimg-amd64-root.tar.gz`
However, it crashed. Then when I use command `bash`, there is an error: 0x80070002.
Since command `lxrun /uninstall /full` can't work now, I wonder how can I uninstall this wrong installation? Any help will be truly appreciated.

**Comment by DDoSolitary** [comment]
?

**Comment by jamietre** [comment]
Same thing happened to me. Install appeared to work, but launching wsl fails with this error. I am able to uninstall it fine with `lxrunoffline uninstall -n ...`, I tried a could different Ubuntu distros (the MS download, and 17.10 from the cloud builds per the wiki) and the same thing happened for both.

**Comment by DDoSolitary** [comment]
Could you please try the [dev builds](https://ci.appveyor.com/project/DDoSolitary/lxrunoffline/build/artifacts)? The problem might be caused by a bug that's fixed but not released yet.

**Comment by DDoSolitary** [comment]
@MtMao As @jamietre mentioned, use `lxrunoffline uninstall` for uninstallation.

**Comment by jamietre** [comment]
@DDoSolitary no change with dev build. 

For the record -the reason I'm doing this at all, instead of just installing it from Microsoft Store, is because something on this machine got screwed up (perhaps fall Creator's Update?) and I can't run the Microsoft Store at all. I discovered this when I went to install wsl; it's never been installed before on this machine before. Maybe the same problem with my config is related. (I tried a hundred different ways to fix the app store but it just won't work; I really couldn't care less about it though except I want to get wsl working!)

**Comment by DDoSolitary** [comment]
Thank you for your information. However, unfortunately, I couldn't reproduce this issue on my local PC.

**Comment by DDoSolitary** [comment]
Could you please post the output of `lxrunoffline install` so I can investigate why it crashes?

**Comment by DDoSolitary** [comment]
And for the Microsoft Store, have you tried creating a new Windows user? It is how I fixed it when I faced similar issue last time.

**Comment by jamietre** [comment]
There's no output or error, i didn't notice any verbose option either:
 ```
> lxrunoffline install -n ubuntu -f c:\temp\16.04.2-server-cloudimg-amd64-root.tar.gz -d c:\wsl\ubuntu
> lxrunoffline list
ubuntu
>
```
However... It's working now, almost -- I have to run `bash` as Administrator (or launch from CLI in an elevated shell). Pretty sure I tried as admin before, since I was working in an elevated shell all along, and definitely tried to start from the cli. Maybe this is a consequence of installing this from an elevated shell? Seems strange.

I've done a few other things in the meantime related to trying to fix the store issue (I just can't give up) which could be related: Deleted `HKCU\Software\Microsoft\Windows\CurrentVersion\CloudStore\Store\Cache`. [Fixed permissions on Runtime Broker ](https://www.tenforums.com/performance-maintenance/20230-windows-10-event-id-10010-10016-errors-distributedcom-2.html#post523625)which was filling app log with errors. Rebooted a few times. 

Re: microsoft store - still not working - yeah, i tried everything: created new user, wsreset, manually remove/reinstall store, spent hours trying every possible solution I could find. Nothing has any effect. I hate leaving things in a known bad state on this box, but it's a media server and I don't really care about much other than that it works ;) so I'm not going to reinstall windows or whatever. Never even tried to use the ms store before now.

**Comment by DDoSolitary** [comment]
> There's no output or error, I didn't notice any verbose option either:

As a typical command line program, no output indicates a success. BTW, I have plans to add a verbose option.

> I have to run bash as Administrator.

Normally it doesn't require admin privilege. Did you run `lxrunoffline install` as admin?

> And I can't have more than one shell open

If you run the first bash instance as admin, you'll have to run all others as admin, too. It is a limitation from Windows.

**Comment by jamietre** [comment]
> Did you run lxrunoffline install as admin

I did. I just tried it without being elevated, and it doesn't work:

```
> lxrunoffline install -n ubuntu -f c:\temp\16.04.2-server-cloudimg-amd64-root.tar.gz -d c:\wsl\ubuntu
Error: 80070005
```
The fact that I can't run it except as admin is definitely a problem, but at least I can run it now.

**Comment by DDoSolitary** [comment]
I think it is because you're installing into a location where only admins can access: `c:\wsl\ubuntu`, so neither `lxrunoffline` nor `bash` can run without admin privileges. It is expected behavior.

**Comment by jamietre** [comment]
I just changed it to full control for `Users`, and still can't install w/o elevated:

![image](https://user-images.githubusercontent.com/573056/34461768-80ca99ce-ee01-11e7-977e-e034350ad591.png)

Also tried making a folder within regular user's home and installing it there also didn't work w/o elevated.

**Comment by DDoSolitary** [comment]
Could you please try to run other commands like `LxRunOffline list` and `LxRunOffline default`?

**Comment by MtMao** [comment]
@DDoSolitary  I have already tried `LxRunOffline uninstall`, but it crashed:
```
PS C:\WINDOWS\system32> LxRunOffline list
Ubuntu
PS C:\WINDOWS\system32> LxRunOffline uninstall -n Ubuntu

System.UnauthorizedAccessException: Access denied for path "CommandLine.dll"
    In System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
    In System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)

    In LxRunOffline.Wsl.UninstallDistro(String distroName)
    In LxRunOffline.Program.<>c.<Main>b__0_4(UninstallOptions opts)
    In LxRunOffline.Program.Main(String[] args)
```
I cannot find any other solution so I just reinstall my Windows. Hope this will be fixed in a new version :)

**Comment by DDoSolitary** [comment]
@MtMao
Where is your LxRunOffline executable and did you install with admin privileges? And did you get LxRunOffline using Chocolatey?
Currently your Ubuntu installation is corrupt so LxRunOffline wants to delete the directory containing itself. To solve this, run `LxRunOffline unregister -n Ubuntu` and delete the `rootfs` directory which is in the same directory as `LxRunOffline.exe`.

**Comment by MtMao** [comment]
@DDoSolitary 
Well, I exactly got LxRunOffline by choco. I run `LxRunOffline unregister -n Ubuntu` then delete `C:\ProgramData\Chocolatey\lib\lxrunoffline\tools\rootfs`, finally it works. Thanks a lot for your help!

And do you mean that we should not use LxRunOffline via choco to install something?

**Comment by jamietre** [comment]
When there's an instance installed (which I can only do from the admin shell)

```
> lxrunoffline list
ubuntu
> lxrunoffline default
ubuntu
```

When nothing is installed:

```
> lxrunoffline list

> lxrunoffline default

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: name
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at Microsoft.Win32.RegistryKey.ValidateKeyName(String name)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at LxRunOffline.Wsl.GetDefaultDistro()
   at LxRunOffline.Program.<>c.<Main>b__0_1(DefaultOptions opts)
   at LxRunOffline.Program.Main(String[] args)
```

**Comment by jamietre** [comment]
@DDoSolitary Figured it out --

I had installed via chocolatey as administrator. It doesn't actually work if you try to `choco install` as a non-elevated user since admin rights are required to write to `ProgramData/chocolatey`. (Maybe there are other ways to use chocolately I don't know about -- I have always installed things as admin)

Something I did along the way gave me a more revealing error:

```
>  lxrunoffline install -n ubuntu -f c:\temp\16.04.2-server-cloudimg-amd64-root.tar.gz -d c:\wsl\ubuntu

Unhandled Exception: System.IO.IOException: Access to the path 'C:\ProgramData\chocolatey\lib\lxrunoffline\tools\rootfs' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at LxRunOffline.Wsl.InstallDistro(String distroName, String tarGzPath, String targetPath)
   at LxRunOffline.Program.<>c.<Main>b__0_2(InstallOptions opts)
   at LxRunOffline.Program.Main(String[] args)
```


If I give myself access to `C:\ProgramData\chocolatey\lib\lxrunoffline` before trying to run `lxrunoffline install` it works.

I don't know too much about this but it seems like the need to write to a folder within the chocolatey installation after `lxrunoffline` is already installed is not a good thing, since the user may not have access to do that?

Also, when installs and uninstalls fail, things get left in a messy state. `lxrunoffline uninstall` will fail, and `lxrunoffline install` will fail saying the name already exists. You can use `unregister` and then manually delete the assets to get around this, but seems like it should exit more cleanly or maybe add a cleanup/force option to uninstall that doesn't care if things don't seem to be in the expected state in case this happens?

**Comment by DDoSolitary** [comment]
@MtMao @jamietre Thank you for your information. Then it turns out that the problem is caused by my choco package. Because of the limitations of the `WslRegisterDistribution` Win API function, `lxrunoffline install` has to write to the directory where it is in, but Chocolatey install files to a location where only admins can write by default (`C:\ProgramData\chocolatey\lib\lxrunoffline`). I've already discovered the problem and submitted a new package that installs to `C:\tools\lxrunoffline`, where regular users can access, to Chocolatey. Unfortunately, most moderators of Chocolatey are busy on holidays now so you have to either install the new package via `choco install lxrunoffline -version 2.1.2` or download the binaries directly from GitHub Releases.
