### ISSUE TITLE
[ERROR] Filesystem version 0 is not recognized.

### ISSUE THREAD

**Issue by mqmq0** [DDoSolitary/LxRunOffline#81]
E:\LxRunOffline-v3.3.3>LxRunOffline move -n Legacy -d "D:\WSL"
[ERROR] Filesystem version 0 is not recognized.

How to solve?

**Comment by DDoSolitary** [comment]
Is it a legacy distro installed by lxrun/bash?

**Comment by mqmq0** [comment]
Yes, it was installed by `lxrun /install`

**Comment by DDoSolitary** [comment]
Please try the latest dev build mentioned in readme to verify if it's been fixed.

**Comment by mqmq0** [comment]
`E:\LxRunOffline-v3.3.3-4-gf750ada>LxRunOffline move -n Legacy -d "D:\WSL"`

Okay, now it ran, gave some warnings like this:
`[WARNING] Ignoring an unsupported file "\\?\C:\Users\MYUSER\AppData\Local\lxss\rootfs\dev\tty4" of type 0020000`
Finished without error, 
but

`E:\LxRunOffline-v3.3.3-4-gf750ada>bash.exe
Performing one-time upgrade of the Windows Subsystem for Linux file system for this distribution...
Error: 0x80070005
Press any key to continue...

E:\LxRunOffline-v3.3.3-4-gf750ada>`

Now bash.exe fails to run.

(If its a big hassle to fix it, then I can install other package, like the one from the MS Store. Probably its works with that)

**Comment by mqmq0** [comment]
In the meantime, I figured, that most of the file were not moved from the Appdatalocal

**Comment by DDoSolitary** [comment]
If there are files inside `rootfs` not moved, it's most likely that the program crashed during the moving operation. Unfortunately, Microsoft has removed lxrun.exe from the latest insider preview build I'm using now, so I'll have to set up a VM to try to reproduce your issue, which might take quite some time. Thus if you don't want to wait, you can use the store apps as you said, or install using the images whose download links are available in the wiki. BTW, lxrun.exe has been deprecated by Microsoft so I don't recommend using it without don't particularly reason.

And could you please provide some more information, which will be helpful for me the reproduce and fix this issue:
- Your Windows version
- Is the distro you're moving a clean one or you have used it for some time? If not, does it work if you move a clean one?
- What happens if you try to move a distro installed by a store app to the desired location
- What happens if you use the `duplicate` command, which copies the distro, instead of `move` 

Thanks!

**Comment by mqmq0** [comment]
* Your Windows version
W10 Pro 1803 build 17134.590
* Is the distro you're moving a clean one or you have used it for some time? If not, does it work if you move a clean one?
New-ish. Just installed, and set up graphic support

* What happens if you try to move a distro installed by a store app to the desired location
Ubuntu1804 moved like a charm
* What happens if you use the `duplicate` command, which copies the distro, instead of `move`
same

Now I'm out of the wood with ubuntu1804, so no hurry from my side. 
But  I can help to debug this if you want. Is there a point to do so, if lxrun will be removed soon? 
I just found some old guide on google how to setup WSL with graphic apps, and followed that, that's how I end up here.

**Comment by DDoSolitary** [comment]
I just successfully reproduced this on a VM. I found out that there's a bug that the source directory isn't deleted after moving, so the files left in `LOCALAPPDATA` are irrelevant to this issue and can be safely delete manually. The `0x80070005` error is likely to be caused by the fact that the program actually produces filesystem v1 but the `Version` registry key is still 0.

**Comment by DDoSolitary** [comment]
I think it makes sense to support lxrun.exe. Although the executable has been removed since v1809, it is still present in v1803, which is stated to be supported in readme. Also it's possible that a distro created by lxrun.exe exists on a supported system which is upgraded from v1803 or even earlier.

**Comment by DDoSolitary** [comment]
Root caused found: v0 and v1 filesystem has different directory layouts. v1 puts everything under `rootfs` but v0 has other special directories like `home` and `root` placed outside of `rootfs`. So LxRunOffline doesn't set a required case sensitivity flag on these special folders (in fact, it doesn't even create them). When launching the distro, WSL detects this and tries to fix this: `Performing one-time upgrade of the Windows Subsystem for Linux file system for this distribution...`, but this operation requires a special permission which isn't granted by default on an external disk (#42) and LxRunOffline doesn't grant it as well for the same reason, so we get 0x80070005 (Access denied).

My plan is:
- Implement a new reader for v0 filesystems, which transparently maps the special directories to `rootfs` for writers to use.
- Automatically change `Version` from 0 to 1 after `move`/`duplicate`.

This will also fix the known bug that the contents of the home directory will be lost after manipulating on Legacy distros.

Althogh it is possible to implement a writer v0 filesystems and leave `Version` to be 0, which actually obeys the semantics of "move" and "duplicate", it makes much less sense to support writing than reading for something that has been deprecated.

@mqmq0 Could you please help test it when I get the updates ready?

**Comment by mqmq0** [comment]
Yeah, sure. I just installed a fresh Legacy distro.
I wont update my W10 for a while, so I can help.

**Comment by DDoSolitary** [comment]
@mqmq0 Could you please post the names of the directories under `%localappdata%\lxss` so that I can determine the exact list of the directories that needs to be mapped into rootfs. (I can't access my v1803 VM in several days.)

**Comment by mqmq0** [comment]
Ok, read your edit later then generating this, so here you go nevertheless:

https://pastebin.com/AvuF5EGH

Expires in a day.

**Comment by 742362144** [comment]
> `E:\LxRunOffline-v3.3.3-4-gf750ada>LxRunOffline move -n Legacy -d "D:\WSL"`
> 
> Okay, now it ran, gave some warnings like this:
> `[WARNING] Ignoring an unsupported file "\\?\C:\Users\MYUSER\AppData\Local\lxss\rootfs\dev\tty4" of type 0020000`
> Finished without error,
> but
> 
> ```
> `E:\LxRunOffline-v3.3.3-4-gf750ada>bash.exe
> Performing one-time upgrade of the Windows Subsystem for Linux file system for this distribution...
> Error: 0x80070005
> Press any key to continue...
> 
> E:\LxRunOffline-v3.3.3-4-gf750ada>`
> ```
> Now bash.exe fails to run.
> 
> (If its a big hassle to fix it, then I can install other package, like the one from the MS Store. Probably its works with that)

i have the same problem as u

**Comment by 742362144** [comment]
> `E:\LxRunOffline-v3.3.3-4-gf750ada>LxRunOffline move -n Legacy -d "D:\WSL"`
> 
> 好吧，现在它跑了，给出了一些这样的警告：
> `[WARNING] Ignoring an unsupported file "\\?\C:\Users\MYUSER\AppData\Local\lxss\rootfs\dev\tty4" of type 0020000`
> 完成没有错误，
> 但是
> 
> ```
> `E:\LxRunOffline-v3.3.3-4-gf750ada>bash.exe
> Performing one-time upgrade of the Windows Subsystem for Linux file system for this distribution...
> Error: 0x80070005
> Press any key to continue...
> 
> E:\LxRunOffline-v3.3.3-4-gf750ada>`
> ```
> 现在bash.exe无法运行。
> 
> （如果解决这个问题很麻烦，那么我可以安装其他软件包，比如MS Store中的软件包。可能是它的工作原理）

i solve this problem. i just installed my ubuntu but not start and init it. i guess this tool cant't find the rootfs path if u do not init the system.
1. start ubuntu in app store
2. init the system (like set your username and pwd).then exit
3.  rerty the lxrunoffline move  command
everything is ok. ：）

**Comment by DDoSolitary** [comment]
Fix is almost ready

**Comment by hermanocabral** [comment]
any news on this issue?

**Comment by DDoSolitary** [comment]
I'm sorry but it's only two months before the college entrance exam in China and I'm extremely busy and have little time for this. I'm still working on it but I can't give any ETA.

**Comment by DDoSolitary** [comment]
The bug should have been fixed. Please try the latest dev release and let me know if you encounter any problems.
