### ISSUE TITLE
WSL 2

### ISSUE THREAD

**Issue by FreakLevel** [DDoSolitary/LxRunOffline#92]
I have a lot of questions but is only for try to help you, I love this project.

- This project have totally support of wsl 2? I need make something to use?

- Is possible connect usb devices to the subsystems? Like for work with android and use adb services.

- How can I help you to improve this project?

Thank you for create this, now I can develop using win 10 happiest.

**Comment by DDoSolitary** [comment]
- This project have totally support of wsl 2? I need make something to use?

Only limited support because it's hard to read/write vhdx files. https://github.com/DDoSolitary/LxRunOffline/issues/90#issuecomment-510318620
The feature hasn't yet been released so you have to use [dev releases](https://ci.appveyor.com/project/DDoSolitary/lxrunoffline).

- Is possible connect usb devices to the subsystems? Like for work with android and use adb services.

USB support is not related to this project, please consult Microsoft.
FYI current status:
WSL1: Only storage devices
WSL2：Not supported, but Microsoft promised that it will be supported in the future

Also, if you just want to work with Android you could try adb over network.

- How can I help you to improve this project?

Currently all planned features have been implemented so most of the work is maintenance. Any help is welcome, including:
- Answer questions in issues
- Discuss possible implementation of feature requests
- Open issues/PRs for bugs and feature requests
- Improve error messages in `error.cpp` (I'm not a native English speaker)
- Remind me of any updates on WSL from Microsoft
Thanks a lot for your volunteering 😄
