### ISSUE TITLE
Suggest AppVeyor

### ISSUE THREAD

**Issue by FreakLevel** [DDoSolitary/LxRunOffline#94]
This doesn't affect nothing but I think you should remove your api_key and auth_token from the appveyor.yml and set on the environment of AppVeyor website.

![Screen Shot 2019-08-06 at 1 27 19 PM](https://user-images.githubusercontent.com/29663603/62561809-f55cc100-b84d-11e9-8252-c5889f2d3033.png)

**Comment by DDoSolitary** [comment]
That doesn't matter in terms of security because the values are encrypted using the [secure variables](https://www.appveyor.com/docs/build-configuration/#secure-variables) feature of AppVeyor. Personally I prefer keeping all of the CI configuration that don't change frequently in appveyor.yml and use the web UI only for debugging.

**Comment by FreakLevel** [comment]
Thank you, I wasn't know about the secure variables, you're right.
