### ISSUE TITLE
Can't uninstall distribution

### ISSUE THREAD

**Issue by dustinlacewell** [DDoSolitary/LxRunOffline#95]
I deleted the data path backing a distribution managed by LxRunOffline. But now I cannot uninstall it because it can't find the path.

```
PS C:\> LxRunOffline.exe l
Ubuntu
test
DisunityTemplate

PS C:\> LxRunOffline.exe ui -n DisunityTemplate
[ERROR] Couldn't open the directory "\\?\C:\wsl\DisunityTemplate\".
Reason: The system cannot find the path specified.
```

**Comment by DDoSolitary** [comment]
The distribution should be already properly uninstalled. A distribution installation consists of two parts: registry keys and files. The command first tried to delete the registry keys and completed successfully (because there aren't any relevant error messages). And then it tried to delete files and failed as expected. If you list your distributions again, you'll find the one to be deleted disappeared.

However, in your case, the recommended way is to clean up the distribution is to use the `unregister`/'ur` command, which only deletes the registry keys and leave the files as is.

**Comment by dustinlacewell** [comment]
Thanks for the information. You should copy paste this into the readme :)
